### PR TITLE
I359 programmatically query results

### PR DESCRIPTION
**Pull request by fcooper8472**
See #350.

Current shortcomings are:
* Can only handle a single output being requested at a time
* Testing is inadequate: can't yet figure out how to mock a working store that includes all the components necessary to test the `get_results()` method.
  * This can be most easily done by using the sample project, but this avenue has been ruled out in favour of fixtures (see #304)

### CODE REVIEW

**Comment by willu47** [comment]
I'm happy with the functionality now. @tomalrussell wanted to have a look through the testing options for you @fcooper8472, so over to him.

**Comment by fcooper8472** [comment]
> @tomalrussell wanted to have a look through the testing options for you @fcooper8472, so over to him.

That would be really helpful - I've been struggling to mock a "complete" state that includes the necessary model runs, sector models and results.  If we could work out how to provide that in a fixture it would be useful more widely, but would definitely allow us to thoroughly test this.

**Comment by fcooper8472** [comment]
I'm in the process of tinkering with the fixtures to improve the test coverage - but happy for you to merge this now and look at further changes down the line if you prefer?

**Comment by tomalrussell** [comment]
I'll pick this up on Tuesday afternoon and aim to cut 1.1 (#369) - a bit of tinkering and coverage would be welcome if you can fit it in before then.

**Pull request merged**
