### PR TITLE
Feature/geography conversion

### PR DESCRIPTION
**Pull request by tomalrussell**
[Aiming to deliver #138601355]

Needs thinking through corner cases, likely more test cases needed.

### CODE REVIEW

**Comment by willu47** [comment]
rtree issue solved with conda install [`conda install -c ioos rtree=0.8.2`](https://anaconda.org/IOOS/rtree)  (which installs `libspatialindex`)

**Comment by willu47** [comment]
```shell
_____________________ ERROR collecting tests/cli/test_cli.py ______________________
ImportError while importing test module '/Users/will2/repository/nismod/smif/tests/cli/test_cli.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/cli/test_cli.py:10: in <module>
    from smif.cli import (confirm, parse_arguments, setup_project_folder,
smif/cli/__init__.py:46: in <module>
    from smif.data_layer.sector_model_config import SectorModelReader
smif/data_layer/sector_model_config.py:8: in <module>
    import fiona
../../../miniconda3/envs/smif/lib/python3.5/site-packages/fiona/__init__.py:72: in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
../../../miniconda3/envs/smif/lib/python3.5/site-packages/fiona/collection.py:7: in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
E   ImportError: dlopen(/Users/will2/miniconda3/envs/smif/lib/python3.5/site-packages/fiona/ogrext.cpython-35m-darwin.so, 2): Library not loaded: @loader_path/./libgssapi_krb5.2.2.dylib
E     Referenced from: /Users/will2/miniconda3/envs/smif/lib/libgdal.20.dylib
E     Reason: image not found
__________ ERROR collecting tests/data_layer/test_sector_model_config.py __________
ImportError while importing test module '/Users/will2/repository/nismod/smif/tests/data_layer/test_sector_model_config.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/data_layer/test_sector_model_config.py:6: in <module>
    from smif.data_layer.sector_model_config import SectorModelReader
smif/data_layer/sector_model_config.py:8: in <module>
    import fiona
../../../miniconda3/envs/smif/lib/python3.5/site-packages/fiona/__init__.py:72: in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
../../../miniconda3/envs/smif/lib/python3.5/site-packages/fiona/collection.py:7: in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
E   ImportError: dlopen(/Users/will2/miniconda3/envs/smif/lib/python3.5/site-packages/fiona/ogrext.cpython-35m-darwin.so, 2): Library not loaded: @loader_path/./libgssapi_krb5.2.2.dylib
E     Referenced from: /Users/will2/miniconda3/envs/smif/lib/libgdal.20.dylib
E     Reason: image not found
```

**Comment by willu47** [comment]
Also, see failed travis tests for similar issues!

**Comment by tomalrussell** [comment]
Yes - merging into v0.2 now. Let's review and design validation/shared implementation after 0.1 release.

**Comment by willu47** [comment]
👍

**Pull request merged**
