### PR TITLE
Feature/time spent

### PR DESCRIPTION
**Pull request by RoaldL**
This pull request suggest a mechanism for basic profiling in smif (providing a summary of job run times). The feature requires at least verbosity level 1 (-v).

This resolves: https://www.pivotaltracker.com/story/show/162700102

Example outputs:
```
INFO     ******************************************************************************************************************************************************
INFO     build_model_run      energy_water_cp_cr                                                               00:00:00
INFO     modelrun.run         energy_water_cp_cr                                                               00:00:02
INFO     | JobScheduler._run()  graph_0                                                                          00:00:02
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_before_model_run_water_sector_energy_demand               00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2020_0_water_sector_energy_demand                00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2015_0_water_sector_energy_demand                00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2010_0_water_sector_energy_demand                00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_before_model_run_reservoir_level                          00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2020_0_reservoir_level                           00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2015_0_reservoir_level                           00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2010_0_reservoir_level                           00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_before_model_run_climate                                  00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2020_0_climate                                   00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2015_0_climate                                   00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2010_0_climate                                   00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_before_model_run_population                               00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2020_0_population                                00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2015_0_population                                00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2010_0_population                                00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_before_model_run_energy_demand                            00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2020_0_energy_demand                             00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2015_0_energy_demand                             00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2010_0_energy_demand                             00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_before_model_run_water_supply                             00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2010_0_water_supply                              00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2015_0_water_supply                              00:00:00
INFO     | | JobScheduler._run()  job_energy_water_cp_cr_simulate_2020_0_water_supply                              00:00:00
INFO     ******************************************************************************************************************************************************
Model run 'energy_water_cp_cr' complete
```

```
INFO     ******************************************************************************************************************************************************
INFO     build_model_run      energy_central                                                                   00:00:00
INFO     modelrun.run         energy_central                                                                   00:00:00
INFO     | JobScheduler._run()  graph_0                                                                          00:00:00
INFO     | | JobScheduler._run()  job_energy_central_before_model_run_water_sector_energy_demand                   00:00:00
INFO     | | JobScheduler._run()  job_energy_central_simulate_2010_1_water_sector_energy_demand                    00:00:00
INFO     | | JobScheduler._run()  job_energy_central_before_model_run_population                                   00:00:00
INFO     | | JobScheduler._run()  job_energy_central_simulate_2010_1_population                                    00:00:00
INFO     | | JobScheduler._run()  job_energy_central_before_model_run_energy_demand                                00:00:00
INFO     | | JobScheduler._run()  job_energy_central_simulate_2010_1_energy_demand                                 00:00:00
INFO     | JobScheduler._run()  graph_1                                                                          00:00:00
INFO     | | JobScheduler._run()  job_energy_central_simulate_2015_2_water_sector_energy_demand                    00:00:00
INFO     | | JobScheduler._run()  job_energy_central_simulate_2015_2_population                                    00:00:00
INFO     | | JobScheduler._run()  job_energy_central_simulate_2015_2_energy_demand                                 00:00:00
INFO     | JobScheduler._run()  graph_2                                                                          00:00:00
INFO     | | JobScheduler._run()  job_energy_central_simulate_2020_3_water_sector_energy_demand                    00:00:00
INFO     | | JobScheduler._run()  job_energy_central_simulate_2020_3_population                                    00:00:00
INFO     | | JobScheduler._run()  job_energy_central_simulate_2020_3_energy_demand                                 00:00:00
INFO     ******************************************************************************************************************************************************
Model run 'energy_central' complete
```

### CODE REVIEW

**Comment by willu47** [comment]
Running energy_supply_minimal on nismod2 I get:
```
INFO     ******************************************************************************************************************************************************
INFO     | | JobScheduler._run()  job_energy_supply_minimal_simulate_2015_0_es_prices                              00:00:00                                          
INFO     | | JobScheduler._run()  job_energy_supply_minimal_before_model_run_dummy_energy_demands_minimal          00:00:00                                          
INFO     | JobScheduler._run()  graph_0                                                                          00:00:40                                          
INFO     build_model_run      energy_supply_minimal                                                            00:00:00                                          
INFO     | | JobScheduler._run()  job_energy_supply_minimal_before_model_run_es_prices                             00:00:00                                          
INFO     modelrun.run         energy_supply_minimal                                                            00:00:40                                          
INFO     | | JobScheduler._run()  job_energy_supply_minimal_simulate_2015_0_energy_supply_toy                      00:00:39                                          
INFO     | | JobScheduler._run()  job_energy_supply_minimal_before_model_run_energy_supply_toy                     00:00:00                                          
INFO     | | JobScheduler._run()  job_energy_supply_minimal_simulate_2015_0_dummy_energy_demands_minimal           00:00:00                                          
INFO     ******************************************************************************************************************************************************
```

A few observations:
- Note the different order of the jobs to the sample project examples - this makes the structure less obvious
- I think it would be good to see a clear total time for the model run as a separate entry.
- It would also be nice to separate the summary from the rest of the logging more clearly, and also provide a heading to the table.

**Comment by RoaldL** [comment]
@willu47 - I have processed your comments, the list is now correctly sorted and displays the information that you've requested. Let me know what you think.

**Comment by RoaldL** [comment]
```
INFO     **************************************************** Modelrun time profile *****************************************************
INFO     Function                      Operation                                                                       Time [hh:mm:ss]
INFO     ********************************************************************************************************************************
INFO     run_model_runs                energy_water_cp_cr, local_csv, src/smif/sample_project/                         00:00:02
INFO     | build_model_run               energy_water_cp_cr                                                              00:00:00
INFO     | modelrun.run                  energy_water_cp_cr                                                              00:00:02
INFO     | | JobScheduler._run()           graph_0                                                                         00:00:02
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_before_model_run_water_sector_energy_demand              00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2020_0_water_sector_energy_demand               00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2015_0_water_sector_energy_demand               00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2010_0_water_sector_energy_demand               00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_before_model_run_reservoir_level                         00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2020_0_reservoir_level                          00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2015_0_reservoir_level                          00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2010_0_reservoir_level                          00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_before_model_run_climate                                 00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2020_0_climate                                  00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2015_0_climate                                  00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2010_0_climate                                  00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_before_model_run_population                              00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2020_0_population                               00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2015_0_population                               00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2010_0_population                               00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_before_model_run_energy_demand                           00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2020_0_energy_demand                            00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2015_0_energy_demand                            00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2010_0_energy_demand                            00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_before_model_run_water_supply                            00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2010_0_water_supply                             00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2015_0_water_supply                             00:00:00
INFO     | | | JobScheduler._run()           job_energy_water_cp_cr_simulate_2020_0_water_supply                             00:00:00
INFO     ********************************************************************************************************************************
```

**Comment by RoaldL** [comment]
```
INFO     **************************************************** Modelrun time profile *****************************************************
INFO     Function                      Operation                                                                       Time [hh:mm:ss]
INFO     ********************************************************************************************************************************
INFO     run_model_runs                energy_central, local_csv, src/smif/sample_project/                             00:00:01
INFO     | build_model_run               energy_central                                                                  00:00:00
INFO     | modelrun.run                  energy_central                                                                  00:00:00
INFO     | | JobScheduler._run()           graph_0                                                                         00:00:00
INFO     | | | JobScheduler._run()           job_energy_central_before_model_run_water_sector_energy_demand                  00:00:00
INFO     | | | JobScheduler._run()           job_energy_central_simulate_2010_1_water_sector_energy_demand                   00:00:00
INFO     | | | JobScheduler._run()           job_energy_central_before_model_run_population                                  00:00:00
INFO     | | | JobScheduler._run()           job_energy_central_simulate_2010_1_population                                   00:00:00
INFO     | | | JobScheduler._run()           job_energy_central_before_model_run_energy_demand                               00:00:00
INFO     | | | JobScheduler._run()           job_energy_central_simulate_2010_1_energy_demand                                00:00:00
INFO     | | JobScheduler._run()           graph_1                                                                         00:00:00
INFO     | | | JobScheduler._run()           job_energy_central_simulate_2015_2_water_sector_energy_demand                   00:00:00
INFO     | | | JobScheduler._run()           job_energy_central_simulate_2015_2_population                                   00:00:00
INFO     | | | JobScheduler._run()           job_energy_central_simulate_2015_2_energy_demand                                00:00:00
INFO     | | JobScheduler._run()           graph_2                                                                         00:00:00
INFO     | | | JobScheduler._run()           job_energy_central_simulate_2020_3_water_sector_energy_demand                   00:00:00
INFO     | | | JobScheduler._run()           job_energy_central_simulate_2020_3_population                                   00:00:00
INFO     | | | JobScheduler._run()           job_energy_central_simulate_2020_3_energy_demand                                00:00:00
INFO     ********************************************************************************************************************************
```

**Comment by willu47** [comment]
Looks good @RoaldL - final niggles would be to try to right align each of the entries in the Time column, and change the heading from `Time` to `Duration`.  Otherwise, great, and very useful!

**Pull request merged**
